# Pandas 1 Review

This is a quick review of core Pandas concepts before we start our in-class activity.  
All examples use a small (and intentionally messy) healthcare dataset for demonstration purposes.

Covered concepts:
- Creating a DataFrame
- Inspecting data
- Accessing columns
- Identifying and handling missing values
- Removing duplicates
- Filtering (basic conditions only)
- Using `apply()` for simple transformations (extra: used in the module example code)
- Introduction to Exceptions (extra: used in the module example code)

In [1]:

import pandas as pd
import numpy as np

data = {
    'PatientID': [1, 2, 3, 4, 5, 5],
    'Age': [25, 40, np.nan, 60, 29, 29],
    'Gender': ['F', 'M', 'M', 'F', np.nan, np.nan],
    'Smoker': [0, 1, 0, np.nan, 0, 0],
    'BMI': [22.0, 30.5, 27.8, 31.2, 23.5, 23.5]
}

df = pd.DataFrame(data)
df

   PatientID   Age Gender  Smoker   BMI
0          1  25.0      F     0.0  22.0
1          2  40.0      M     1.0  30.5
2          3   NaN      M     0.0  27.8
3          4  60.0      F     NaN  31.2
4          5  29.0    NaN     0.0  23.5
5          5  29.0    NaN     0.0  23.5

## Inspecting a DataFrame

We can check the structure of a DataFrame with:
- `df.head()` → first 5 rows
- `df.info()` → structure and data types
- `df.describe()` → summary statistics for numeric columns

In [2]:
print(df.head())
print(df.info())
print(df.describe())

   PatientID   Age Gender  Smoker   BMI
0          1  25.0      F     0.0  22.0
1          2  40.0      M     1.0  30.5
2          3   NaN      M     0.0  27.8
3          4  60.0      F     NaN  31.2
4          5  29.0    NaN     0.0  23.5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PatientID  6 non-null      int64
 1   Age        5 non-null      float64
 2   Gender     4 non-null      object
 3   Smoker     5 non-null      float64
 4   BMI        6 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 368.0+ bytes
None
       PatientID       Age    Smoker        BMI
count   6.000000   5.00000  5.000000   6.000000
mean    3.333333  36.60000  0.200000  26.416667
std     1.632993  14.22322  0.447214   3.949388
min     1.000000  25.00000  0.000000  22.000000
25%     2.250000  29.00000  0.000000  23.500000
50%     3.500000  29.00000  0.000000  25.650000
75%     4.750000  40.00000  0.000000  29.825000
max     5.000000  60.00000  1.000000  31.200000

## Accessing Data

You can access columns like this:
- `df['Age']` → returns the Age column
- `df[['Age', 'BMI']]` → returns multiple columns

In [3]:
print(df['Age'])
print(df[['Age', 'BMI']])

0    25.0
1    40.0
2     NaN
3    60.0
4    29.0
5    29.0
Name: Age, dtype: float64
    Age   BMI
0  25.0  22.0
1  40.0  30.5
2   NaN  27.8
3  60.0  31.2
4  29.0  23.5
5  29.0  23.5

## Identifying and Handling Missing Values

You can detect missing values:
- `df.isnull()` → shows missing values as True/False
- `df.isnull().sum()` → shows count of missing values per column

You can fill missing values:
- `df['Age'].fillna(value)` → fill missing Age values

In [4]:
print(df.isnull())
print("\nMissing values per column:\n", df.isnull().sum())

# Example: fill missing Age with the median
df['Age'] = df['Age'].fillna(df['Age'].median())
print("\nAfter filling missing Age values:\n", df)

   PatientID    Age  Gender  Smoker    BMI
0      False  False   False   False  False
1      False  False   False   False  False
2      False   True   False   False  False
3      False  False   False    True  False
4      False  False    True   False  False
5      False  False    True   False  False

Missing values per column:
 PatientID    0
Age          1
Gender       2
Smoker       1
BMI          0
dtype: int64

After filling missing Age values:
    PatientID   Age Gender  Smoker   BMI
0          1  25.0      F     0.0  22.0
1          2  40.0      M     1.0  30.5
2          3  29.0      M     0.0  27.8
3          4  60.0      F     NaN  31.2
4          5  29.0    NaN     0.0  23.5
5          5  29.0    NaN     0.0  23.5

## Removing Duplicates

You can remove duplicated rows:
- `df.duplicated()` → shows duplicated rows as True/False
- `df.drop_duplicates()` → removes duplicated rows

In [5]:
print("\nDuplicated rows:\n", df.duplicated())
df = df.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", df)

Duplicated rows:
 0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

DataFrame after removing duplicates:
    PatientID   Age Gender  Smoker   BMI
0          1  25.0      F     0.0  22.0
1          2  40.0      M     1.0  30.5
2          3  29.0      M     0.0  27.8
3          4  60.0      F     NaN  31.2
4          5  29.0    NaN     0.0  23.5

## Basic Filtering

You can select rows by conditions:
- Example: select all female patients (`Gender == 'F'`)
- Example: select all patients older than 40

In [6]:
females = df[df['Gender'] == 'F']
print("All female patients:\n", females)

older_patients = df[df['Age'] > 40]
print("\nPatients older than 40:\n", older_patients)

All female patients:
    PatientID   Age Gender  Smoker   BMI
0          1  25.0      F     0.0  22.0
3          4  60.0      F     NaN  31.2

Patients older than 40:
    PatientID   Age Gender  Smoker   BMI
3          4  60.0      F     NaN  31.2

## Exception Handling in Python

Exception handling lets you catch and manage errors that would normally stop your program.

Basic structure:
```python
try:
    # code that might raise an error
except ExceptionType:
    # what to do if the error occurs

In [7]:
def safe_divide(a, b):
    try:
        result = a / "b"
        return result
    except Exception as e:
        return e

print(safe_divide(10, 2))   # normal division
print(safe_divide(5, 0))    # triggers exception

unsupported operand type(s) for /: 'int' and 'str'
unsupported operand type(s) for /: 'int' and 'str'

## Common Exception Types in Python

Here are some of the most commonly encountered exceptions:

| Exception | Description |
|----------|-------------|
| `ZeroDivisionError` | Raised when dividing by zero |
| `ValueError` | Raised when a function receives an argument of correct type but invalid value |
| `TypeError` | Raised when an operation is applied to an object of inappropriate type |
| `IndexError` | Raised when accessing an invalid index of a list or sequence |
| `KeyError` | Raised when a dictionary key is not found |
| `FileNotFoundError` | Raised when trying to open a non-existing file |

### Example: `ValueError`:

In [8]:
def convert_to_int(value):
    try:
        return int(value)
    except ValueError:
        return "Cannot convert to integer."

print(convert_to_int("25"))      # Works fine
print(convert_to_int("hello"))   # Raises ValueError, caught by exception

25
Cannot convert to integer.

# Reading the Peregrine Falcon dataset

Let’s read the **Peregrine Falcon - NYSDEC.csv** dataset.  
This dataset contains **GPS tracking records of peregrine falcons monitored in North America**, including timestamps, coordinates, and individual identifiers.  

We will analyze this dataset to understand its structure, check data types, and prepare it for further exploration.  
Let’s start by reading the data and previewing the first few rows.

In [9]:
# Your code here
df = pd.read_csv(r'Peregrine Falcon - NYSDEC.csv')
df

,event-id,visible,timestamp,location-long,location-lat,algorithm-marked-outlier,argos:altitude,argos:best-level,argos:calcul-freq,argos:error-radius,...,argos:sensor-1,argos:sensor-2,argos:sensor-3,argos:sensor-4,argos:valid-location-algorithm,sensor-type,individual-taxon-canonical-name,tag-local-identifier,individual-local-identifier,study-name
0,94477883,True,2012-05-30 09:21:03.000,-78.815,42.950,NaN,171.0,-134.0,401.672660,NaN,...,150,144,2,2,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
1,94477885,True,2012-05-30 11:43:18.000,-78.886,42.986,NaN,166.0,-134.0,401.672491,NaN,...,5,5,0,0,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
2,94477887,True,2012-05-30 13:42:34.000,-78.833,42.964,NaN,151.0,-127.0,401.672555,NaN,...,177,160,3,2,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
3,94477888,True,2012-05-30 15:01:26.000,-78.799,42.947,NaN,175.0,-121.0,401.672573,NaN,...,172,160,1,2,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
4,94477891,True,2012-05-30 17:05:27.000,-78.818,42.956,NaN,164.0,-132.0,401.672604,NaN,...,164,156,1,0,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10483,471579178,True,2005-09-21 03:49:16.000,-81.489,44.025,NaN,257.0,-133.0,401.672289,NaN,...,118,144,1,3,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC
10484,471579179,True,2005-09-22 07:37:22.000,-81.493,44.026,NaN,253.0,-130.0,401.672281,NaN,...,3,69,0,0,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC
10485,471579180,True,2005-09-22 09:04:11.000,-81.489,44.026,NaN,257.0,-130.0,401.672283,NaN,...,120,136,3,3,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC
10486,471579181,True,2005-09-22 12:25:00.000,-81.491,44.025,NaN,255.0,-129.0,401.672265,NaN,...,8,69,0,0,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC
10487,471579183,True,2005-09-23 16:58:04.000,-81.483,44.016,NaN,260.0,-131.0,401.672177,NaN,...,153,116,3,3,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC

## Step 1: Inspect the dataset

Check the structure of the dataset:
- Number of rows and columns
- List of column names
- Basic information about the dataset
- Data types

In [10]:
# Your code here
print(len(df))
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

10488
(10488, 34)
Index(['event-id', 'visible', 'timestamp', 'location-long', 'location-lat',
       'algorithm-marked-outlier', 'argos:altitude', 'argos:best-level',
       'argos:calcul-freq', 'argos:error-radius', 'argos:gdop', 'argos:iq',
       'argos:lat1', 'argos:lat2', 'argos:lc', 'argos:lon1', 'argos:lon2',
       'argos:nb-mes', 'argos:nb-mes-120', 'argos:nopc', 'argos:orientation',
       'argos:pass-duration', 'argos:semi-major', 'argos:semi-minor',
       'argos:sensor-1', 'argos:sensor-2', 'argos:sensor-3', 'argos:sensor-4',
       'argos:valid-location-algorithm', 'sensor-type',
       'individual-taxon-canonical-name', 'tag-local-identifier',
       'individual-local-identifier', 'study-name'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10488 entries, 0 to 10487
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   event-id                         10488 non-null  int64
 1   visible                          10488 non-null  bool
 2   timestamp                        10488 non-null  object
 3   location-long                    10383 non-null  float64
 4   location-lat                     10383 non-null  float64
 5   algorithm-marked-outlier         0 non-null      float64
 6   argos:altitude                   10488 non-null  float64
 7   argos:best-level                 10488 non-null  float64
 8   argos:calcul-freq                10488 non-null  float64
 9   argos:error-radius               160 non-null    float64
 10  argos:gdop                       160 non-null    float64
 11  argos:iq                         10488 non-null  int64
 12  argos:lat1                       10488 non-null  float64
 13  argos:lat2                       10488 non-null  float64
 14  argos:lc                         10488 non-null  int64
 15  argos:lon1                       10488 non-null  float64
 16  argos:lon2                       10488 non-null  float64
 17  argos:nb-mes                     10488 non-null  int64
 18  argos:nb-mes-120                 10488 non-null  int64
 19  argos:nopc                       10488 non-null  int64
 20  argos:orientation                160 non-null    float64
 21  argos:pass-duration              10488 non-null  float64
 22  argos:semi-major                 160 non-null    float64
 23  argos:semi-minor                 160 non-null    float64
 24  argos:sensor-1                   10488 non-null  int64
 25  argos:sensor-2                   10488 non-null  int64
 26  argos:sensor-3                   10488 non-null  int64
 27  argos:sensor-4                   10488 non-null  int64
 28  argos:valid-location-algorithm   10488 non-null  int64
 29  sensor-type                      10488 non-null  object
 30  individual-taxon-canonical-name  10488 non-null  object
 31  tag-local-identifier             10488 non-null  int64
 32  individual-local-identifier      10488 non-null  object
 33  study-name                       10488 non-null  object
dtypes: bool(1), float64(16), int64(12), object(5)
memory usage: 2.7+ MB
None
           event-id  location-long  location-lat  algorithm-marked-outlier  \
count  1.048800e+04   10383.000000  10383.000000                       0.0
mean   4.779678e+08     -77.363061     43.477560                       NaN
std    1.141059e+08       3.177465      0.853793                       NaN
min    9.447788e+07     -84.232000     40.700000                       NaN
25%    4.691320e+08     -79.349000     43.360500                       NaN
50%    4.691358e+08     -78.813000     43.767000                       NaN
75%    4.691405e+08     -76.951000     43.919000                       NaN
max    1.844475e+09     -69.345000     46.248000                       NaN

       argos:altitude  argos:best-level  argos:calcul-freq  \
count    10488.000000      10488.000000       1.048800e+04
mean        86.233410       -127.945461       6.128118e+06
std         77.522297          4.185696       4.923427e+07
min          0.000000       -137.000000       4.016424e+02
25%         39.000000       -131.000000       4.016722e+02
50%         88.000000       -128.000000       4.016722e+02
75%        128.000000       -125.000000       4.016722e+02
max       3355.000000       -105.000000       4.016723e+08

       argos:error-radius   argos:gdop      argos:iq  ...  argos:orientation  \
count          160.000000   160.000000  10488.000000  ...         160.000000
mean           434.225000   667.675000     58.716342  ...          87.768750
std            417.964684   485.172051      7.455568  ...          20.979541
min            153.000000   222.000000     40.000000  ...          35.000000
25%            213.000000   385.000000     56.000000  ...          74.750000
50%            284.000000   519.000000     58.000000  ...          85.500000
75%            476.500000   709.500000     66.000000  ...          97.000000
max           3550.000000  3288.000000     68.000000  ...         166.000000

       argos:pass-duration  argos:semi-major  argos:semi-minor  \
count         10488.000000        160.000000        160.000000
mean            459.815694       3003.518750        109.631250
std             168.384888       5619.289898        105.132598
min             120.000000        202.000000         22.000000
25%             342.000000        564.500000         54.000000
50%             443.000000       1018.000000         77.500000
75%             583.000000       2297.000000        126.000000
max             931.000000      36085.000000        878.000000

       argos:sensor-1  argos:sensor-2  argos:sensor-3  argos:sensor-4  \
count    10488.000000    10488.000000    10488.000000    10488.000000
mean        84.128528      137.406655        1.137777        1.809020
std         72.971687       58.974005        1.166010        6.363773
min          0.000000        1.000000        0.000000        0.000000
25%          6.000000      100.000000        0.000000        0.000000
50%        116.000000      148.000000        1.000000        0.000000
75%        154.000000      188.000000        2.000000        2.000000
max        255.000000      255.000000        3.000000       63.000000

       argos:valid-location-algorithm  tag-local-identifier
count                    10488.000000          10488.000000
mean                         1.006102          58836.213291
std                          0.077882           4675.440910
min                          1.000000          37123.000000
25%                          1.000000          59783.000000
50%                          1.000000          59783.000000
75%                          1.000000          59783.000000
max                          2.000000          67521.000000

[8 rows x 28 columns]

## Note:
When we inspect the dataset’s structure using `df.info()`, we’ll notice that the **`timestamp` column** is listed as having a **`object`** data type.  
This means Pandas is treating the timestamps as plain text, which prevents proper time-based operations.  

To fix this, we need to **convert the `timestamp` column into datetime format** using `pd.to_datetime()`.

In [11]:
# Your code here
df["timestamp"].apply(pd.to_datetime)
# df["timestamp"] = pd.to_datetime(df["timestamp"])

0       2012-05-30 09:21:03
1       2012-05-30 11:43:18
2       2012-05-30 13:42:34
3       2012-05-30 15:01:26
4       2012-05-30 17:05:27
                ...
10483   2005-09-21 03:49:16
10484   2005-09-22 07:37:22
10485   2005-09-22 09:04:11
10486   2005-09-22 12:25:00
10487   2005-09-23 16:58:04
Name: timestamp, Length: 10488, dtype: datetime64[ns]

## A better way (passing the column names that are date time)
Check the Pandas documentation for `pd.read_csv()` to see how `parse_dates` works:

In [12]:
# Your code here

df_parce = pd.read_csv(r'Peregrine Falcon - NYSDEC.csv', parse_dates=["timestamp"])
df_parce.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10488 entries, 0 to 10487
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   event-id                         10488 non-null  int64
 1   visible                          10488 non-null  bool
 2   timestamp                        10488 non-null  datetime64[ns]
 3   location-long                    10383 non-null  float64
 4   location-lat                     10383 non-null  float64
 5   algorithm-marked-outlier         0 non-null      float64
 6   argos:altitude                   10488 non-null  float64
 7   argos:best-level                 10488 non-null  float64
 8   argos:calcul-freq                10488 non-null  float64
 9   argos:error-radius               160 non-null    float64
 10  argos:gdop                       160 non-null    float64
 11  argos:iq                         10488 non-null  int64
 12  argos:lat1                       10488 non-null  float64
 13  argos:lat2                       10488 non-null  float64
 14  argos:lc                         10488 non-null  int64
 15  argos:lon1                       10488 non-null  float64
 16  argos:lon2                       10488 non-null  float64
 17  argos:nb-mes                     10488 non-null  int64
 18  argos:nb-mes-120                 10488 non-null  int64
 19  argos:nopc                       10488 non-null  int64
 20  argos:orientation                160 non-null    float64
 21  argos:pass-duration              10488 non-null  float64
 22  argos:semi-major                 160 non-null    float64
 23  argos:semi-minor                 160 non-null    float64
 24  argos:sensor-1                   10488 non-null  int64
 25  argos:sensor-2                   10488 non-null  int64
 26  argos:sensor-3                   10488 non-null  int64
 27  argos:sensor-4                   10488 non-null  int64
 28  argos:valid-location-algorithm   10488 non-null  int64
 29  sensor-type                      10488 non-null  object
 30  individual-taxon-canonical-name  10488 non-null  object
 31  tag-local-identifier             10488 non-null  int64
 32  individual-local-identifier      10488 non-null  object
 33  study-name                       10488 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(16), int64(12), object(4)
memory usage: 2.7+ MB

## Step 2: Identify missing values

Check how many missing values exist per column.

In [13]:
# Your code here
df.isnull().sum()

event-id                               0
visible                                0
timestamp                              0
location-long                        105
location-lat                         105
algorithm-marked-outlier           10488
argos:altitude                         0
argos:best-level                       0
argos:calcul-freq                      0
argos:error-radius                 10328
argos:gdop                         10328
argos:iq                               0
argos:lat1                             0
argos:lat2                             0
argos:lc                               0
argos:lon1                             0
argos:lon2                             0
argos:nb-mes                           0
argos:nb-mes-120                       0
argos:nopc                             0
argos:orientation                  10328
argos:pass-duration                    0
argos:semi-major                   10328
argos:semi-minor                   10328
argos:sensor-1                         0
argos:sensor-2                         0
argos:sensor-3                         0
argos:sensor-4                         0
argos:valid-location-algorithm         0
sensor-type                            0
individual-taxon-canonical-name        0
tag-local-identifier                   0
individual-local-identifier            0
study-name                             0
dtype: int64

### Display columns with at least one missing value

In [14]:
# Display columns with at least one missing value
missing_summary =  df[df.columns[df.isnull().sum() > 0]]
# Your code here
missing_summary.columns

Index(['location-long', 'location-lat', 'algorithm-marked-outlier',
       'argos:error-radius', 'argos:gdop', 'argos:orientation',
       'argos:semi-major', 'argos:semi-minor'],
      dtype='object')

## Step 4: Drop Columns with Missing Values

Create a list of column names containing missing values (`missing_columns`),  
and drop those columns if you think they have too many missing entries, e.g., **more than 90% of the values are missing**.  
This helps reduce noise and keeps the dataset focused on useful information.

In [15]:
df_notnull = df.drop(columns=missing_summary.columns[2:])
df_notnull

,event-id,visible,timestamp,location-long,location-lat,argos:altitude,argos:best-level,argos:calcul-freq,argos:iq,argos:lat1,...,argos:sensor-1,argos:sensor-2,argos:sensor-3,argos:sensor-4,argos:valid-location-algorithm,sensor-type,individual-taxon-canonical-name,tag-local-identifier,individual-local-identifier,study-name
0,94477883,True,2012-05-30 09:21:03.000,-78.815,42.950,171.0,-134.0,401.672660,50,42.950,...,150,144,2,2,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
1,94477885,True,2012-05-30 11:43:18.000,-78.886,42.986,166.0,-134.0,401.672491,55,42.986,...,5,5,0,0,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
2,94477887,True,2012-05-30 13:42:34.000,-78.833,42.964,151.0,-127.0,401.672555,56,42.964,...,177,160,3,2,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
3,94477888,True,2012-05-30 15:01:26.000,-78.799,42.947,175.0,-121.0,401.672573,67,42.947,...,172,160,1,2,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
4,94477891,True,2012-05-30 17:05:27.000,-78.818,42.956,164.0,-132.0,401.672604,57,42.956,...,164,156,1,0,1,argos-doppler-shift,Falco,67521,PEFA 1687-01341 50/AD,Peregrine Falcon - NYSDEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10483,471579178,True,2005-09-21 03:49:16.000,-81.489,44.025,257.0,-133.0,401.672289,60,44.025,...,118,144,1,3,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC
10484,471579179,True,2005-09-22 07:37:22.000,-81.493,44.026,253.0,-130.0,401.672281,68,44.026,...,3,69,0,0,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC
10485,471579180,True,2005-09-22 09:04:11.000,-81.489,44.026,257.0,-130.0,401.672283,60,44.026,...,120,136,3,3,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC
10486,471579181,True,2005-09-22 12:25:00.000,-81.491,44.025,255.0,-129.0,401.672265,68,44.025,...,8,69,0,0,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC
10487,471579183,True,2005-09-23 16:58:04.000,-81.483,44.016,260.0,-131.0,401.672177,40,44.016,...,153,116,3,3,1,argos-doppler-shift,Falco,59782,PEFA 1687-01182 2/S,Peregrine Falcon - NYSDEC

## Step 5: Access Specific Columns

Let’s take a look at a few key columns — `timestamp`, `location-lat`, and `location-long` —  
to preview the tracking data and ensure they were loaded correctly.

In [16]:
# Your code here
df_notnull[["timestamp", "location-long", "location-lat"]]

                     timestamp  location-long  location-lat
0      2012-05-30 09:21:03.000        -78.815        42.950
1      2012-05-30 11:43:18.000        -78.886        42.986
2      2012-05-30 13:42:34.000        -78.833        42.964
3      2012-05-30 15:01:26.000        -78.799        42.947
4      2012-05-30 17:05:27.000        -78.818        42.956
...                        ...            ...           ...
10483  2005-09-21 03:49:16.000        -81.489        44.025
10484  2005-09-22 07:37:22.000        -81.493        44.026
10485  2005-09-22 09:04:11.000        -81.489        44.026
10486  2005-09-22 12:25:00.000        -81.491        44.025
10487  2005-09-23 16:58:04.000        -81.483        44.016

[10488 rows x 3 columns]

## Step 6: Drop Rows with Missing Critical Values

In our tracking dataset, the **critical columns** are `timestamp`, `location-lat`, and `location-long`,  
as each observation must have valid spatial and temporal information.  

Even though these columns typically have no missing values,  
we should still check and drop any incomplete rows to keep our dataset clean and reliable for analysis.

In [17]:
# Your code here
df_notnull.dropna(inplace=True)

## Example: Simple use of exception handling

Try accessing a column that does not exist. Like this:
```python
df['NonExistentColumn'].head()

In [18]:
df['NonExistentColumn'].head()

KeyError: 'NonExistentColumn'

### Note:
You will get an error. The error type is **KeyError**, as you can see at the end of the error message.

You can catch that error and display a custom message like this:

In [ ]:
# Your code here

## Step 7: Extract datetime components from the timestamp

Once your `timestamp` column is in datetime format, you can easily extract useful date and time parts.

Create new columns for:
- `year` → year of observation
- `month` → month of observation
- `day` → day of the month
- `hour` → hour of the day
- `minute` → minute of the hour
- `weekday` → day of the week (0 = Monday, 6 = Sunday)

In [ ]:
# Your code here

## Step 8: Find the date range of the tracking study

Find the overall time span of the tracking dataset by finding the earliest and latest recorded timestamps.

In [ ]:
# Your code here

## Step 9: Exploring the dataset using value_counts()

You can explore any categorical column in your DataFrame using `value_counts()`.  
This will show how many times each unique value appears in that column.

- Which falcon has the most data points?
- You will use that falcon's data for the rest of the tasks.

In [ ]:
# Your code here

## Step10: Filter the dataset for one specific falcon

Now filter the dataset to create a smaller DataFrame for only that falcon that has the most number of observations. Call it **my_falcon_data**.

In [ ]:
# Your code here

## Step 11: Filter dataset for specific values using isin()
Overwrite my_falcon_data to have only records from the years **2008** and **2012**.

You can filter based on a list of values using the `isin()` function. For example, to select rows where a column has values "A" or "B", use:
```python
df_filtered = df[df['column_name'].isin(['A', 'B'])]

In [ ]:
# Your code here

## Step 12: A function to visualize tracking points on a map

**IMPORTANT:**  
**This is not part of your required module content.**

You are not expected to understand how this function works at this stage.  
You will learn about mapping and more advanced functions later in the course.

### For now:
1. Use your `my_falcon_data` DataFrame (already filtered for the correct falcon and years).
2. Pass the relevant columns to the function:
   - `latitude column`  
   - `longitude column`  
   - `year column`
3. Enjoy the interactive map with an on/off control for each year! **Do you see any difference in the points collected from that falcon in the two years?**

### You may need to install folium once by running:
pip install folium

In [ ]:
import folium

def simple_folium_year_map(latitudes, longitudes, years):
    """
    Very simple helper function for MSc students.
    Plots points on Folium map, grouped by year with layer control.
    Different colors for each year.
    """
    # Define a simple list of colors
    colors = ['red', 'blue', 'green', 'orange', 'purple', 'black', 'brown']
    
    # Create base map at mean location
    m = folium.Map(location=[latitudes.mean(), longitudes.mean()], zoom_start=6)
    
    unique_years = sorted(years.dropna().unique())
    
    # Loop over unique years
    for idx, year in enumerate(unique_years):
        year_points = (years == year)
        fg = folium.FeatureGroup(name=str(int(year)))
        
        # Pick color (cycle if more years than colors)
        color = colors[idx % len(colors)]
        
        # Add all points for that year
        for lat, lon in zip(latitudes[year_points], longitudes[year_points]):
            folium.CircleMarker(
                location=[lat, lon],
                radius=3,
                color=color,
                fill=True,
                fill_opacity=0.7
            ).add_to(fg)
        
        fg.add_to(m)

    folium.LayerControl().add_to(m)
    return m

In [ ]:
m = simple_folium_year_map(
    latitudes = # Your code here,
    longitudes = # Your code here,
    years = # Your code here
)
#m.save("falcon_map.html")
m

SyntaxError: invalid syntax (3860986098.py, line 3)

In [27]:
import pandas as pd

data = pd.read_csv("products_Sample v2.csv")

In [32]:
data.to_csv("products_Sample v2.csv", sep=",", encoding="ASCII")

UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 19: ordinal not in range(128)

In [29]:
data.to_excel("products_Sample v2.xlsx", index=False)

In [2]:
# import Decimal from decimal
from decimal import Decimal
a =  {'ClientDateID': '47fd40ac79fb4444a7b22d3090a3b6e8#2025-09-11', 'counter': Decimal('-8'), 'ttl': Decimal('1757635200')}

In [3]:
len(a)

3