# Pandas Series

## Creating a Series:

### Creating a Series from a List:

In [1]:
import pandas as pd

# Creating a Series from a list
data_series = pd.Series([1, 2, 3, 4, 5])
print(data_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

### Creating a Series from a Dictionary:

In [2]:
import pandas as pd

# Creating a Series from a dictionary
data_dict = {'a': 10, 'b': 20, 'c': 30}
data_series_dict = pd.Series(data_dict)
print(data_series_dict)

a    10
b    20
c    30
dtype: int64

## Series Labels (Index)

### Custom Index:

In [3]:
import pandas as pd

# Creating a Series with a custom index
data_series = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(data_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

### Accessing Elements Using Labels:

In [4]:
import pandas as pd

# Creating a Series with a custom index
data_series = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

# Accessing elements using labels
print(data_series['a'])
print(data_series[['a', 'c', 'e']])

1
a    1
c    3
e    5
dtype: int64

### Modifying Index:

In [5]:
import pandas as pd

# Creating a Series
data_series = pd.Series([1, 2, 3, 4, 5])

# Modifying the index
data_series.index = ['a', 'b', 'c', 'd', 'e']
print(data_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

### Inspecting a Series

In [6]:
import pandas as pd

# Sample Series
data_series = pd.Series([1, 2, 3, 4, 5])

# Displaying the first few elements
print(data_series.head(2))

# Displaying the last few elements
print(data_series.tail(2))

# Generating descriptive statistics
print(data_series.describe())

0    1
1    2
dtype: int64
3    4
4    5
dtype: int64
count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

# Pandas DataFrames

## Creating a DataFrame

In [7]:
import pandas as pd

# Creating a DataFrame from a dictionary of lists
data_dict = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29]
}
data_frame = pd.DataFrame(data_dict)
print(data_frame)

   Name  Age
0  John   28
1  Jane   24
2   Tom   35
3  Lucy   29

## Basic Methods to Inspect a DataFrame

In [8]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29],
    'Salary': [70000, 80000, 120000, 90000]
}
df = pd.DataFrame(data)

# Displaying the first few rows
print(df.head())

# Displaying the last few rows
print(df.tail())

# Getting a concise summary of the DataFrame
print(df.info())

# Generating descriptive statistics
print(df.describe())

   Name  Age  Salary
0  John   28   70000
1  Jane   24   80000
2   Tom   35  120000
3  Lucy   29   90000
   Name  Age  Salary
0  John   28   70000
1  Jane   24   80000
2   Tom   35  120000
3  Lucy   29   90000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes
None
             Age         Salary
count   4.000000       4.000000
mean   29.000000   90000.000000
std     4.546061   21602.468995
min    24.000000   70000.000000
25%    27.000000   77500.000000
50%    28.500000   85000.000000
75%    30.500000   97500.000000
max    35.000000  120000.000000

## Basic DataFrame Operations

### 1.	Selecting Data:

In [9]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29],
    'Salary': [70000, 80000, 120000, 90000]
}
df = pd.DataFrame(data)

In [10]:
# Selecting a single column
print(df['Name'])

0    John
1    Jane
2     Tom
3    Lucy
Name: Name, dtype: object

In [11]:
# Selecting multiple columns
print(df[['Name', 'Salary']])

   Name  Salary
0  John   70000
1  Jane   80000
2   Tom  120000
3  Lucy   90000

In [12]:
# Selecting rows using labels (loc)
print(df.loc[0])  # Selecting the first row

Name       John
Age          28
Salary    70000
Name: 0, dtype: object

In [13]:
# Selecting rows using positions (iloc)
print(df.iloc[0])  # Selecting the first row

Name       John
Age          28
Salary    70000
Name: 0, dtype: object

### 2.	Filtering Data:

In [14]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29],
    'Salary': [70000, 80000, 120000, 90000]
}
df = pd.DataFrame(data)

# Filtering rows where Age is greater than 30
filtered_df = df[df['Age'] > 30]
print(filtered_df)

  Name  Age  Salary
2  Tom   35  120000

### 3.	Adding and Modifying Columns:

In [15]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29],
    'Salary': [70000, 80000, 120000, 90000]
}
df = pd.DataFrame(data)

# Adding a new column
df['Bonus'] = [5000, 6000, 8000, 7000]
print(df)

   Name  Age  Salary  Bonus
0  John   28   70000   5000
1  Jane   24   80000   6000
2   Tom   35  120000   8000
3  Lucy   29   90000   7000

### 4.	Dropping Columns and Rows:

In [16]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29],
    'Salary': [70000, 80000, 120000, 90000]
}
df = pd.DataFrame(data)

# Dropping a column
df_dropped_column = df.drop('Age', axis=1)
df_dropped_column

   Name  Salary
0  John   70000
1  Jane   80000
2   Tom  120000
3  Lucy   90000

In [17]:
# Dropping a row
df_dropped_row = df.drop(0, axis=0)
df_dropped_row

   Name  Age  Salary
1  Jane   24   80000
2   Tom   35  120000
3  Lucy   29   90000

# Data Loading with Pandas

## Practical Exercises

### Loading Data from a CSV File

In [18]:
# Loading the sample CSV file with your own path
#Python is case sensitive
#use df = pd.read_csv(r'C:\unf python\car_sales_data.csv') if you use backslashes (\) instead of forward slashes (/)
df = pd.read_csv('C:/unf python/car_sales_data.csv')

# Displaying the first few rows
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:/unf python/car_sales_data.csv'

### Loading Data from an Excel File

In [ ]:
import pandas as pd

# Loading the sample Excel file
df = pd.read_excel('C:/unf python/car_sales_data.xlsx', sheet_name='car_sales_data')

# Displaying the first few rows
df.head()

,Date,Salesperson,Customer Name,Car Make,Car Model,Car Year,Sale Price,Commission Rate,Commission Earned
0,2022-08-01,Monica Moore MD,Mary Butler,Nissan,Altima,2018,15983,0.070495,1126.73
1,2023-03-15,Roberto Rose,Richard Pierce,Nissan,F-150,2016,38474,0.134439,5172.40
2,2023-04-29,Ashley Ramos,Sandra Moore,Ford,Civic,2016,33340,0.114536,3818.63
3,2022-09-04,Patrick Harris,Johnny Scott,Ford,Altima,2013,41937,0.092191,3866.20
4,2022-06-16,Eric Lopez,Vanessa Jones,Honda,Silverado,2022,20256,0.113490,2298.85

# Data Inspection and Cleaning

## Inspecting the Structure of a DataFrame:

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29],
    'Salary': [70000, 80000, 120000, 90000]
}
df = pd.DataFrame(data)

# Displaying the first few rows
df.head()

   Name  Age  Salary
0  John   28   70000
1  Jane   24   80000
2   Tom   35  120000
3  Lucy   29   90000

In [ ]:
# Displaying the last few rows
df.tail()

   Name  Age  Salary
0  John   28   70000
1  Jane   24   80000
2   Tom   35  120000
3  Lucy   29   90000

In [ ]:
# Getting a concise summary of the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
# Generating descriptive statistics
df.describe()

             Age         Salary
count   4.000000       4.000000
mean   29.000000   90000.000000
std     4.546061   21602.468995
min    24.000000   70000.000000
25%    27.000000   77500.000000
50%    28.500000   85000.000000
75%    30.500000   97500.000000
max    35.000000  120000.000000

In [ ]:
# Getting the dimensions of the DataFrame
df.shape

(4, 3)

In [ ]:
# Getting the column labels
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [ ]:
# Getting the row labels
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
# Getting the data types of each column
df.dtypes

Name      object
Age        int64
Salary     int64
dtype: object

## Handling Missing Values

### 1)	Identifying Missing Values:

In [ ]:
import pandas as pd

# Sample DataFrame with missing values
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, None, 35, 29],
    'Salary': [70000, 80000, None, 90000]
}
df = pd.DataFrame(data)

In [ ]:
# Identifying missing values
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False

In [ ]:
# Counting missing values per column
df.isnull().sum()

Name      0
Age       1
Salary    1
dtype: int64

### 2)	Handling Missing Values:

In [ ]:
import pandas as pd

# Sample DataFrame with missing values
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, None, 35, 29],
    'Salary': [70000, 80000, None, 90000]
}
df = pd.DataFrame(data)

# Dropping rows with any missing values
df_dropped = df.dropna()
df_dropped

   Name   Age   Salary
0  John  28.0  70000.0
3  Lucy  29.0  90000.0

In [ ]:
# Dropping columns with any missing values
df_dropped_columns = df.dropna(axis=1)
df_dropped_columns

   Name
0  John
1  Jane
2   Tom
3  Lucy

In [ ]:
# Filling missing values with a constant
df_filled = df.fillna(0)
df_filled

   Name   Age   Salary
0  John  28.0  70000.0
1  Jane   0.0  80000.0
2   Tom  35.0      0.0
3  Lucy  29.0  90000.0

In [ ]:
# Forward fill
df_ffill = df.ffill()
df_ffill

   Name   Age   Salary
0  John  28.0  70000.0
1  Jane  28.0  80000.0
2   Tom  35.0  80000.0
3  Lucy  29.0  90000.0

In [ ]:
# Backward fill
df_bfill = df.bfill()
df_bfill

   Name   Age   Salary
0  John  28.0  70000.0
1  Jane  35.0  80000.0
2   Tom  35.0  90000.0
3  Lucy  29.0  90000.0

## Data Types Conversion

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29],
    'Salary': [70000, 80000, 120000, 90000]
}
df = pd.DataFrame(data)

# Identifying data types
df.dtypes

Name      object
Age        int64
Salary     int64
dtype: object

In [ ]:
# Converting data type of 'Age' to float
df['Age'] = df['Age'].astype(float)
df.dtypes

Name       object
Age       float64
Salary      int64
dtype: object

In [ ]:
# Converting data type of 'Salary' to string
df['Salary'] = df['Salary'].astype(str)
df.dtypes

Name       object
Age       float64
Salary     object
dtype: object

## Converting Columns to DateTime

### 1.	Basic Conversion

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'date_strings': ['2023-07-21', '2023-07-22', '2023-07-23']
}
df = pd.DataFrame(data)

# Convert to datetime
df['date'] = pd.to_datetime(df['date_strings'])
df, df.dtypes

(  date_strings       date
 0   2023-07-21 2023-07-21
 1   2023-07-22 2023-07-22
 2   2023-07-23 2023-07-23,
 date_strings            object
 date            datetime64[ns]
 dtype: object)

### 2.	Custom Date Format

In [ ]:
data = {
    'date_strings': ['21/07/2023', '22/07/2023', '23/07/2023']
}
df = pd.DataFrame(data)

# Convert to datetime with custom format
df['date'] = pd.to_datetime(df['date_strings'], format='%d/%m/%Y')
df

  date_strings       date
0   21/07/2023 2023-07-21
1   22/07/2023 2023-07-22
2   23/07/2023 2023-07-23

### 3.	Handling Different Date Formats

In [ ]:
import pandas as pd
from dateutil import parser

data = {
    'date_strings': ['2023-07-21', '21/07/2023', 'July 21, 2023']
}
df = pd.DataFrame(data)

def parse_date(date_string):
    formats = ['%Y-%m-%d', '%d/%m/%Y', '%B %d, %Y']
    for fmt in formats:
        try:
            return pd.to_datetime(date_string, format=fmt)
        except (ValueError, TypeError):
            continue
    try:
        return parser.parse(date_string)
    except (ValueError, TypeError):
        return pd.NaT

# Apply the function to the date_strings column
df['date_times'] = df['date_strings'].apply(parse_date)

df

    date_strings date_times
0     2023-07-21 2023-07-21
1     21/07/2023 2023-07-21
2  July 21, 2023 2023-07-21

### 4.	Including Time Information

In [ ]:
data = {
    'datetime_strings': ['2023-07-21 14:30:00', '2023-07-22 16:45:00', '2023-07-23 09:00:00']
}
df = pd.DataFrame(data)

# Convert to datetime
df['datetime'] = pd.to_datetime(df['datetime_strings'])
df, df.dtypes

(      datetime_strings            datetime
 0  2023-07-21 14:30:00 2023-07-21 14:30:00
 1  2023-07-22 16:45:00 2023-07-22 16:45:00
 2  2023-07-23 09:00:00 2023-07-23 09:00:00,
 datetime_strings            object
 datetime            datetime64[ns]
 dtype: object)

### 5.	Different Time Zones

In [ ]:
data = {
    'datetime_strings': ['2023-07-21 14:30:00', '2023-07-22 16:45:00', '2023-07-23 09:00:00']
}
df = pd.DataFrame(data)

# Convert to datetime with time zone information
df['datetime'] = pd.to_datetime(df['datetime_strings']).dt.tz_localize('UTC')
df

      datetime_strings                  datetime
0  2023-07-21 14:30:00 2023-07-21 14:30:00+00:00
1  2023-07-22 16:45:00 2023-07-22 16:45:00+00:00
2  2023-07-23 09:00:00 2023-07-23 09:00:00+00:00

In [ ]:
# Convert to another time zone
df['datetime_est'] = df['datetime'].dt.tz_convert('US/Eastern')
df

      datetime_strings                  datetime              datetime_est
0  2023-07-21 14:30:00 2023-07-21 14:30:00+00:00 2023-07-21 10:30:00-04:00
1  2023-07-22 16:45:00 2023-07-22 16:45:00+00:00 2023-07-22 12:45:00-04:00
2  2023-07-23 09:00:00 2023-07-23 09:00:00+00:00 2023-07-23 05:00:00-04:00

### 6.	Handling Invalid Dates

In [ ]:
data = {
    'date_strings': ['2023-07-21', 'invalid-date', '2023-07-23']
}
df = pd.DataFrame(data)

# Convert to datetime with error handling
df['date'] = pd.to_datetime(df['date_strings'], errors='coerce')
df

   date_strings       date
0    2023-07-21 2023-07-21
1  invalid-date        NaT
2    2023-07-23 2023-07-23

### 7.	Out-of-Bounds Dates

In [ ]:
import pandas as pd
from datetime import datetime

data = {
    'date_strings': ['2023-07-21', '9999-12-30', '1677-09-20', '2262-04-12']
}
df = pd.DataFrame(data)

# Custom function to handle date conversion
def custom_date_parser(date_str):
    try:
        # Attempt to parse using pandas
        return pd.to_datetime(date_str, errors='raise')
    except (pd.errors.OutOfBoundsDatetime, ValueError):
        # Handle out of bounds dates
        try:
            return datetime.strptime(date_str, '%Y-%m-%d')
        except ValueError:
            return date_str  # Return as string if all parsing fails

# Apply the custom function
df['date'] = df['date_strings'].apply(custom_date_parser)

df

  date_strings                 date
0   2023-07-21  2023-07-21 00:00:00
1   9999-12-30  9999-12-30 00:00:00
2   1677-09-20  1677-09-20 00:00:00
3   2262-04-12  2262-04-12 00:00:00

### 8.	Extracting Date and Time Components

In [ ]:
data = {
    'datetime_strings': ['2023-07-21 14:30:00', '2023-07-22 16:45:00', '2023-07-23 09:00:00']
}
df = pd.DataFrame(data)

# Convert to datetime
df['datetime'] = pd.to_datetime(df['datetime_strings'])

# Extract components
df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour
df['minute'] = df['datetime'].dt.minute
df['second'] = df['datetime'].dt.second

df

,datetime_strings,datetime,year,month,day,hour,minute,second
0,2023-07-21 14:30:00,2023-07-21 14:30:00,2023,7,21,14,30,0
1,2023-07-22 16:45:00,2023-07-22 16:45:00,2023,7,22,16,45,0
2,2023-07-23 09:00:00,2023-07-23 09:00:00,2023,7,23,9,0,0

### 9.	Working with Date Ranges

In [ ]:
# Create a range of dates
date_range = pd.date_range(start='2023-07-21', end='2023-07-27', freq='D')
df = pd.DataFrame(date_range, columns=['date'])

df

        date
0 2023-07-21
1 2023-07-22
2 2023-07-23
3 2023-07-24
4 2023-07-25
5 2023-07-26
6 2023-07-27

## Renaming Columns

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy'],
    'Age': [28, 24, 35, 29],
    'Salary': [70000, 80000, 120000, 90000]
}
df = pd.DataFrame(data)

# Renaming columns
df_renamed = df.rename(columns={'Name': 'Employee Name', 'Age': 'Employee Age', 'Salary': 'Employee Salary'})
df_renamed

  Employee Name  Employee Age  Employee Salary
0          John            28            70000
1          Jane            24            80000
2           Tom            35           120000
3          Lucy            29            90000

## Removing Duplicates

In [ ]:
import pandas as pd

# Sample DataFrame with duplicate rows
data = {
    'Name': ['John', 'Jane', 'Tom', 'Lucy', 'John'],
    'Age': [28, 24, 35, 29, 28],
    'Salary': [70000, 80000, 120000, 90000, 70000]
}
df = pd.DataFrame(data)

# Removing duplicate rows
df_no_duplicates = df.drop_duplicates()
df_no_duplicates

   Name  Age  Salary
0  John   28   70000
1  Jane   24   80000
2   Tom   35  120000
3  Lucy   29   90000

In [ ]:
# Removing duplicate rows based on 'Name' column
df_no_duplicates_name = df.drop_duplicates(subset=['Name'])
df_no_duplicates_name

   Name  Age  Salary
0  John   28   70000
1  Jane   24   80000
2   Tom   35  120000
3  Lucy   29   90000

In [ ]:
# Removing all duplicates, keeping none
df_no_duplicates_all = df.drop_duplicates(keep=False)
df_no_duplicates_all

   Name  Age  Salary
1  Jane   24   80000
2   Tom   35  120000
3  Lucy   29   90000